### ISSUE TITLE
List the members of the batch (read OnbardingBatch contract)

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch1.buidlguidl.com#3]
Show the current members of your batch in the app.

- Show it on the main page or create a page (/builders) listing all the builders registered in the BatchRegistry contract (see #9)
- Each builder should link to their personal profile (see #8)

**Comment by swellander** [comment]
I can tackle this one!

**Comment by carletex** [comment]
Go for it @swellander!!

Thanks

**Comment by JollyRogerz** [comment]
I will also try to tackle this one :)

**Comment by carletex** [comment]
Fixed on #29
