### ISSUE TITLE
Tweak the mainpage

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch1.buidlguidl.com#6]
## Goal

Discuss with your peers what you would like the homepage to show! It can be a good opportunity to tweak the app colors/layout etc.

As in #8, keep it simple (no big images, external assets, etc)

This can be an ongoing issue while you all keep implementing things.

**Comment by dtnwen** [comment]
I would like to propose a  small change to the homepage layout and the overall UI, which would include integrating it with @GusMeg's animated background #34.  ![image](https://github.com/BuidlGuidl/batch1.buidlguidl.com/assets/65008502/23985f23-bc8f-4469-9b08-b31df8a846c3) 

If allowed, I'm ready to code.

**Comment by PrintRH** [comment]
Hello 👋! I would also like to contribute to this issue by adding more features and interactive aspects to our mainpage. I would like to create a typewriter effect highlighting "Buidl Guidl Batch 1" with a link embedded in our image, to integrate with @GusMeg animation in #34 

Here's a demo on what I have built:

https://github.com/BuidlGuidl/batch1.buidlguidl.com/assets/93211672/a5889a47-893c-4e2d-8044-1ef34196b412

To take full advantage of learning with BG fams, I will also submit a PR for feedback 😄

**Comment by carletex** [comment]
Feel free to add more tweaks to it (as in #35), but I think this can be considered "done" :)
