### ISSUE TITLE
Change the logo/title/subtitle

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch1.buidlguidl.com#7]
## Goal

Update your batch's mainpage. 

![image](https://github.com/BuidlGuidl/batch-template/assets/2486142/52a77020-0c08-4136-8cc5-244bc3bd088a)

- Create a random logo (or use Dall-E!) to generate a batch logo
- title: Batch #{batch_number}
- subtitle: Whatever you feel appropriate :)

**Comment by GusMeg** [comment]
I'll do this one
